<?php

define(AUTOTRANSLATED_BOOL_ONOFF, 'On / Off');
define(AUTOTRANSLATED_BOOL_TRUEFALSE, 'True / False');
define(AUTOTRANSLATED_BOOL_YESNO, 'Yes / No');

/**
 * Implementation of hook_field_formatter_info
 */
function autotranslated_bool_field_formatter_info() {
  return array(
    'autotranslated_bool' => array(
      'label' => t('Autotranslated strings'),
      'field types' => array('list_boolean'),
      'settings' => array(
        'type' => 'yesno'
      ),
    ),
  );
}

/**
 * Implementation of hook_field_info_alter()
 */
function autotranslated_bool_field_info_alter(&$info) {
  $info['list_boolean']['settings']['autotranslated_type'] = 'none';
}

function autotranslated_bool_form_field_ui_field_edit_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#field']['type'] !== 'list_boolean') return;

  $element['autotranslated_bool'] = array(
    '#type' => 'select',
    '#title' => 'Autotranslated string',
    '#description' => t('Display default text strings for values, and translate them automatically. PLEASE NOTICE: You have to choose Autotranslated Bool as display mode in Field Format (Manage Display section) for that to happen.'),
    '#options' => _autotranslated_bool_get_options_for_form(true),
    '#default_value' => $form['#field']['settings']['autotranslated_type'],
  );

  $form['field']['settings']['autotranslated_type'] = $element;
  
}


/**
 * Implementation of hook_field_formatter_settings_info
 */
function autotranslated_bool_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $element = array();

  if ($field['type'] === 'list_boolean' && $display['type'] === 'autotranslated_bool') {
    $element['type'] = array(
      '#type' => 'select',
      '#title' => 'Display type',
      '#options' => _autotranslated_bool_get_options_for_form(false),
      '#default_value' => $settings['type'],
    );
  }

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function autotranslated_bool_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  if ($display['type'] !== 'autotranslated_bool')
    return;

  $settings = $display['settings'];

  $summary = '';
  switch($settings['type']) {
    case 'truefalse':
      $summary = t('Values will be shown as True/False');
      break;
    case 'onoff':
      $summary = t('Values will be shown as On/Off');
      break;
    case 'yesno':
    default:
      $summary = t('Values will be shown as Yes/No');
      break;
  }
  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function autotranslated_bool_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $elements = array();
  $type = $display['settings']['type'];

  if (empty($items) || $field['type'] !== 'list_boolean' || $display['type'] != 'autotranslated_bool') {
    return $elements;
  }

  foreach ($items as $delta => $item) {
    if (empty($item['value'])) {
      continue;
    }
    $value = (int) $item['value'];
    $options = _autotranslated_bool_string_list($type);
    $elements[$delta] = array(
      '#markup' => $options[$value],
    );
  }

  return $elements;
}

/**
 * Helper function to return array of option strings from type.
 *
 * @param string $type
 * @return array
 */
function _autotranslated_bool_string_list($type = 'yesno') {
  switch($type) {
    case 'onoff':
      $options = array('Off', 'On');
      break;
    case 'truefalse':
      $options = array('False', 'True');
      break;
    case 'yesno':
    default:
      $options = array('No', 'Yes');

  }
  return $options;
}

/**
 * Helper function to get list of options for Autotranslate strings (used by Form API)
 *
 * @param boolean $include_none
 * @return void
 */
function _autotranslated_bool_get_options_for_form($include_none = false) {
  $options = array();
  if ($include_none) {
    $options['none'] = t('- None -');
  }
  $options['yesno'] = t(AUTOTRANSLATED_BOOL_YESNO);
  $options['truefalse'] = t(AUTOTRANSLATED_BOOL_TRUEFALSE);
  $options['onoff'] = t(AUTOTRANSLATED_BOOL_ONOFF);

  return $options;
}
