stages:
  - deploy

deploy to development:
  stage: deploy
  environment:
    name: development
    url: http://dev.siasar.org
  variables:
    DRUPAL_PATH: "/var/www/drupal_development"
    DB_NAME: "drupal_development"
  script:
    - sudo su postgres -c "/var/lib/pgsql/backup.sh $DB_NAME"
    - sudo rsync -ah --delete --exclude-from=".rsync-exclude" . $DRUPAL_PATH
    - sudo chown -R apache:apache $DRUPAL_PATH
    - sudo su apache -c "drush updb -y --root=$DRUPAL_PATH"
    - sudo su apache -c "drush cc all --root=$DRUPAL_PATH"
  only:
    - develop
