<?php
/**
 * @file
 * Code for the SIASAR Services Config feature.
 */

include_once 'feature_siasar_services.features.inc';


/**
 * Implements hook_services_entity_resource_info().
 */
function feature_siasar_services_services_entity_resource_info() {
  $result = array();

  $result['siasar_entity_processor'] = array(
    'title' => 'SIASAR Entity Processor',
    'description' => 'SIASAR wrapper for entities built on top of Services Clean controller. Data structures are exactly what they are in Drupal.',
    'class' => 'SIASARServicesEntityResourceController',
  );

  return $result;
}

/**
 * Custom access callback to allow public requests to resources.
 *
 * @return bool
 */
function siasar_public_access_callback() {
  return TRUE;
}
