<?php

/**
 * Sets the services entity controller for a custom implementation for SIASAR
 */
function feature_siasar_services_update_7100() {
  variable_set('services_entity_resource_class', 'SIASARServicesEntityResourceController');
}

/**
 * Activate "file" endpoint and deactivate "entity_file"
 */
 function feature_siasar_services_update_7101() {
  features_revert_module('feature_siasar_services');
}
