<?php

/**
 * Implementation of hook_services_request_postprocess_alter().
 * Alter results on the Vocab services call used to retrieve results.
 *
 * @param $controller
 *   Controller definition
 * @param array $args
 *   Arguments passed to services callback
 * @param array $result
 *   Array of results that can be altered
 *
 * @see services_controller_execute()
 * @see services.runtime.inc
 */
function siasar_services_vocab_alter_services_request_postprocess_alter($controller, $args, &$result) {

  if (arg(1) == 'vocab' && $args[0] == 'division_administrativa') {
    _siasar_services_vocab_alter_add_location_codes($result);
  }
}

function _siasar_services_vocab_alter_add_location_codes(&$result) {
  if(empty($result['allowed_values'])) return;

  foreach($result['allowed_values'] as $k => &$r) {
    $term = taxonomy_term_load($k);

    if (isset($term->field_codigo_division_admin[LANGUAGE_NONE][0])) {
      $result['field_codigo_division_admin'][$k] = $term->field_codigo_division_admin[LANGUAGE_NONE][0]['value'];
    }
  }
}