<?php
/**
 * @file
 * Code for the SIASAR Views Reports feature.
 */

include_once 'feature_siasar_views_reports.features.inc';

/**
 * Determines the default location that should be set for the exposed form
 *
 * @param $field_name
 * @param $form_state
 *
 * @return int default location
 */
function _siasar_validate_and_get_default_location($field_name, &$form_state) {
  global $user;

  $user_wrapper = entity_metadata_wrapper('user', $user);
  $location = $user_wrapper->field_entidad_local->value();

  // If the exposed form is being submitted then, make sure it's using valid
  // values. Values might be obtained from the session. Validate them.
  // In this particular case, isset($form_state['input'][$field_name] is equal
  // to know if the user submitted a location. This is only like this as the real
  // field is not exposed and it's actually handled with a custom widget.
  if (isset($form_state['input'][$field_name])) {
    $default_location = $form_state['input'][$field_name];

    // Make sure the $default_location belongs to the user setting
    if (!user_access('assign territorial division') && $location) {
      $parents = taxonomy_get_parents_all($default_location);
      $found = FALSE;
      foreach ($parents as $parent) {
        if ($parent->tid == $location->tid) {
          $found = TRUE;
          break;
        }
      }

      if (!$found) {
        $default_location = $form_state['input'][$field_name] = $location->tid;
      }
    }
  } else {
    $default_location = $location ? $location->tid : null;
  }

  return $default_location;
}

/**
 * Implements hook_form_FORM_ID_alter.
 *
 * Alters exposed filters on view entityform_results_view
 */
function feature_siasar_views_reports_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {

  if ($form_state['view']->name !== 'results_entityforms') return;

  // Inject SIASAR hierarchical Select
  module_load_include('module', 'siasar_field_location', 'siasar_field_location');
  $field_entidad_local = 'field_entidad_local_siasar_hierarchical_select';

  $default_location = _siasar_validate_and_get_default_location($field_entidad_local, $form_state);
  $form[$field_entidad_local] = siasar_field_location_field_widget_skeleton($field_entidad_local, null, $default_location, false, false, false);

  $form['field_pais_iso2'] = _feature_siasar_views_reports_create_country_selector();

  $form['type'] = _feature_siasar_views_reports_create_entityforms_select_field();

  // Country field is only for admins
  if (!user_access('assign territorial division')) {
    $form['field_pais_iso2']['#disabled'] = 'true';
  }
}

/**
 * Creates a select box with all entity type bundles as options
 *
 * @return array
 */
function _feature_siasar_views_reports_create_entityforms_select_field() {
  $form_types = entity_get_info('entityform')['bundles'];
  $user_country_iso2 = _feature_siasar_views_reports_get_user_country();
  $options = array();

  foreach ($form_types as $machine => $type) {
    $options[$machine] = t($type['label']);
  }
  $form_type_selector = array(
    '#type' => 'select',
    '#options' => $options,
    '#required' => false,
    '#empty_option' => t('- All -'),
  );

  $form_type_selector['#default_value'] = _feature_siasar_views_reports_is_valid_country($form_type_selector, $user_country_iso2)
    ? $user_country_iso2
    : '';

  return $form_type_selector;
}

/**
 * Helper function builds country selector
 */
function _feature_siasar_views_reports_create_country_selector() {
  module_load_include('inc', 'siasar_entityform_alter', 'siasar_entityform_alter.helpers');

  $countries = countries_get_countries('name');
  $members = _siasar_entityform_alter_get_member_countries();
  $first_option = array('' => t('- None -'));
  $options = _siasar_entityform_alter_filter_out_countries_from_options($countries, $members);

  $field = array(
    '#type' => 'select',
    '#default_value' => _feature_siasar_views_reports_get_user_country(),
    '#options' => $first_option + $options,
  );

  return $field;
}

/**
 * Helper function checks if user country is a valid option for this country selector.
 * Most country fields are filtered against a list of SIASAR member countries.
 */
 function _feature_siasar_views_reports_is_valid_country($form_field, $country_iso2) {
  $is_valid = isset($form_field['#options'][$country_iso2]);
  return $is_valid;
}


/**
 * Helper function gets user country as entity
 */
function _feature_siasar_views_reports_get_user_country() {
  global $user;
  static $user_country;

  $user_country = !empty($user_country)
    ? $user_country
    : user_load($user->uid)->field_pais[LANGUAGE_NONE][0]['iso2'];

  return $user_country;
}

/**
 * Implementation of hook_theme().
 */
function feature_siasar_views_reports_theme($existing, $type, $theme, $path) {
  $module_path = drupal_get_path('module', 'feature_siasar_views_reports');

  $themes = array();

  $themes['views_view_field__field_status'] = array(
    'original hook' => 'views_view_field',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view_field',
      'feature_siasar_views_reports_preprocess_field_translatable',
    ),
    'variables' => array('view' => NULL, 'field' => NULL, 'row' => NULL, 'output'),
    'template' => 'views-view-field--field-status',
    'path' => $module_path . '/templates',
  );
  $themes['views_view_field__label'] = array(
    'original hook' => 'views_view_field',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view_field',
      'feature_siasar_views_reports_preprocess_field_translatable',
    ),
    'variables' => array('view' => NULL, 'field' => NULL, 'row' => NULL, 'output'),
    'template' => 'views-view-field--label',
    'path' => $module_path . '/templates',
  );

  return $themes;
}

/**
 * Preprocesses translatable field.
 */
function feature_siasar_views_reports_preprocess_field_translatable(&$variables) {
  $variables['output'] = t($variables['output']);
}
