<?php
/**
 * @file
 * Code for the SIASAR Views Reports feature.
 */

include_once 'feature_siasar_views_reports.features.inc';


/**
 * Implements hook_form_FORM_ID_alter.
 * Alters exposed filters on view entityform_results_view
 * TODO: Maybe check a permission instead of a role?
 */
function feature_siasar_views_reports_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form_state['view']->name !== 'results_entityforms') return;

  // Inject SIASAR hierarchical Select
  module_load_include('module', 'siasar_field_location', 'siasar_field_location');
  $field_entidad_local = 'field_entidad_local_siasar_hierarchical_select';
  $form[$field_entidad_local] = siasar_field_location_field_widget_skeleton($field_entidad_local, null, false);


  $form['type'] = _feature_siasar_views_reports_create_entityforms_select_field();
}

function _feature_siasar_views_reports_hide_country_for_non_admins(&$form) {
  global $user;
  $user_country_iso2 = _feature_siasar_views_reports_get_user_country();

  // Country filter is only for admins
  if (!in_array('administrator', $user->roles)) {
    $form['field_pais_iso2']['#type'] = 'hidden';
  }
}

function _feature_siasar_views_reports_create_entityforms_select_field() {
  $form_types = entity_get_info('entityform')['bundles'];
  foreach ($form_types as $machine => $type) {
    $options[$machine] = t($type['label']);
  }
  $form_type_selector = array(
    '#type' => 'select',
    '#options' => $options,
    '#required' => false,
    '#empty_option' => t('- All -'),
  );

  return $form_type_selector;
}

function _feature_siasar_views_reports_get_user_country() {
  global $user;

  $user_country = $user_country
    ? $user_country
    : user_load($user->uid)->field_pais[LANGUAGE_NONE][0]['iso2'];

  return $user_country;
}

/**
 * Implementation of hook_theme().
 */
function feature_siasar_views_reports_theme($existing, $type, $theme, $path) {
  $module_path = drupal_get_path('module', 'feature_siasar_views_reports');

  $themes = array();

  $themes['views_view_field__results_entityforms__draft'] = array(
    'original hook' => 'views_view_field',
    'preprocess functions' => array(
      'template_preprocess',
      'template_preprocess_views_view_field',
      'feature_siasar_views_reports_preprocess_field_draft',
    ),
    'variables' => array('view' => NULL, 'field' => NULL, 'row' => NULL, 'output'),
    'template' => 'views-view-field--results-entityforms--draft',
    'path' => $module_path . '/templates',
  );

  return $themes;

}


/**
 * Preprocesses draft field.
 */
function feature_siasar_views_reports_preprocess_field_draft(&$variables) {
  $output = &$variables['output'];

  $output = ($output == '1')
    ? t('Yes')
    : t('No');

    $variables = $variables;
}
