<?php

/**
 * Alter results on all Entityform Services calls used to retrieve form structure
 *
 * @param $controller
 *   Controller definition
 * @param array $args
 *   Arguments passed to services callback
 * @param array $result
 *   Array of results that can be altered
 *
 * @see services_controller_execute()
 * @see services.runtime.inc
 */
function siasar_services_form_alter_services_request_postprocess_alter($controller, $args, &$result) {

  $allowed_ops = array('retrieve', 'index');

  switch (arg(1)) {
    case 'forms':
      if (is_string(arg(2))) {
        foreach ($result as $key => &$form) {
          _siasar_services_form_alter_process_form($form);
        }
      } else {
        _siasar_services_form_alter_translate_form_names($result);
      }
      break;

    case 'field_group_structure':
      $result = _siasar_services_form_alter_translate_form_group_labels($result);
      break;
  }
}

/**
 * Helper function to process all forms
 */
function _siasar_services_form_alter_process_form(&$form) {
  if (isset($form['field_pais'])) {
    $form['field_pais']['settings']['allowed_values'] = _siasar_services_form_alter_reduce_country_options_to_members();
  }
}

/**
 * Appends field validation information to each entityform field
 *
 * @param $result
 */
function _siasar_services_form_append_validation(&$result) {
  // This is the endpoint for retrieving entityform type's information
  $entity_type = 'entityform';

  ctools_include('export');
  foreach($result as $bundle => &$fields) {

    $rules = ctools_export_load_object('field_validation_rule', 'conditions', array('entity_type' => $entity_type, 'bundle' => $bundle));

    foreach ($fields as $field_name => &$field) {
      siasar_services_form_alter_append_field_validations($bundle, $field, $rules);
    }
  }
}

/**
 * Helper function to get a list of all enabled countries
 * @return array
 */
function _siasar_services_form_alter_get_countries_list() {
  $query = db_query('select iso2, name from countries_country where enabled = 1 order by iso2');
  $result = $query->fetchAll();
  $output = array();

  foreach ($result as $row) {
    $output[$row->iso2] = $row->name;
  }
  return $output;
}

/**
 * Helper function to translate form names
 * @return array
 */
function _siasar_services_form_alter_translate_form_names($result) {
  foreach ($result as $bundle => &$string) {
    $i18n_string_path = 'entityform:entityform_type:'. $bundle .':label';
    $string = i18n_string_translate($i18n_string_path, $string);
  }
}


/**
 * Helper function to translate form group labels
 * @return array
 */
function _siasar_services_form_alter_translate_form_group_labels($result) {
  foreach ($result as &$element) {
    if (is_array($element)) {
      $element = _siasar_services_form_alter_translate_form_group_labels($element);
    } elseif (is_object($element) && isset($element->label)) {
      $element->label = t($element->label);
    }
  }
  return $result;
}


/**
 * Reduce the list of Options for Country selector field to members of SIASAR
 *
 * @return array
 */
function _siasar_services_form_alter_reduce_country_options_to_members() {
  module_load_include('inc', 'siasar_entityform_alter', 'siasar_entityform_alter.helpers');

  $members = _siasar_entityform_alter_get_member_countries();
  $options = _siasar_services_form_alter_get_countries_list();
  return _siasar_entityform_alter_filter_out_countries_from_options($options, $members);
}

/**
 * Append field validation information on each field
 *
 * @param $bundle
 * @param $field
 * @param $rules
 */
function siasar_services_form_alter_append_field_validations($bundle, &$field, $rules) {
  if ($rules) {
    foreach ($rules as $rule) {
      //Disabled by Ctools.
      if (!empty($rule->disabled)) {
        continue;
      }
      ctools_include('plugins');
      $plugin = ctools_get_plugins('field_validation', 'validator', $rule->validator);
      $class = ctools_plugin_get_class($plugin, 'handler');
      if (empty($class)) {
        continue;
      }

      if ($field['field_name'] == $rule->field_name) {
        $field['field_validation_rules'][] = $rule;
      }
    }
  }
}
