<?php

/**
 * Implements hook_menu()
 **/
function siasar_field_location_menu() {
  $items['ajax/location/%/%'] = array(
    'page callback' => 'siasar_field_location_term_list',
    'page arguments' => array(2, 3),
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );
  return $items;
}


/**
 * Implements hook_form_alter()
**/
function siasar_field_location_form_alter(&$form, &$form_state, $form_id) {
  $allowed_form_ids = array(
    'testingpurposes_entityform_edit_form',
  );
  if (!in_array($form_id, $allowed_form_ids)) return;

  $module_path = drupal_get_path('module', 'siasar_field_location');
  drupal_add_js($module_path . '/siasar_field_location.js', array('scope' => 'footer'));
  //drupal_add_css($module_path . '/siasar_field_location.css');
  $form['field_entidad_local'][LANGUAGE_NONE]['#ajax'] = array(
    'callback' => 'siasar_field_location_ajax_callback',
    'wrapper' => 'field-entidad-local-ajax-wrapper',
    'method' => 'replace',
    'effect' => 'none',
  );
  $form['field_entidad_local'][LANGUAGE_NONE]['#prefix'] = '<div id="field-entidad-local-ajax-wrapper">';
  $form['field_entidad_local'][LANGUAGE_NONE]['#suffix'] = '</div>';
  $form['field_entidad_local']['#attributes']['class'][] = 'siasar-hierarchical-select';
}

function siasar_field_location_ajax_callback($form, $form_state) {
  $location_item = $form['field_entidad_local'][LANGUAGE_NONE];
  $value = $form_state['values']['field_entidad_local'][LANGUAGE_NONE][0]['tid'];
  $term = taxonomy_term_load($value);
  $location_item['#options'] = array($term->tid => $term->name);

  return $location_item;
}

/**
 * Returns a list of taxonomy terms for Vocabulary location as JSON
 * It uses a view: division_politica_administrativa:term_reference_location_by_country
 * to get results.
 */
function siasar_field_location_term_list($parent = 0, $country = 'all') {
  $result = '';
  $terms_view = views_get_view('division_politica_administrativa');

  if (is_object($terms_view) ) { 
    $terms_view->set_display('term_reference_location_by_country');
    $terms_view->set_arguments(array($parent, $country));
    $terms_view->execute();
    $result = $terms_view->result;
  }
  $terms_list = _siasar_field_location_map_result_into_term_list($result);

  return drupal_json_output($terms_list);
}

/**
 * Returns an array of [tid] => term name from an array of Taxonomy term objects
 */
function _siasar_field_location_map_result_into_term_list($result) {
  $terms = array();
  foreach ($result as $r) {
    $terms[$r->tid] = $r->taxonomy_term_data_name;
  }
  return $terms;
}
