<?php
/**
 * @file
 * Code for the SIASAR entityform drafts feature.
 */

include_once 'feature_siasar_entityform_drafts.features.inc';

/**
 * Implements hook_module_implements_alter().
 */
function feature_siasar_entityform_drafts_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter' && isset($implementations['feature_siasar_entityform_drafts'])) {
    $group = $implementations['feature_siasar_entityform_drafts'];
    unset($implementations['feature_siasar_entityform_drafts']);
    $implementations['feature_siasar_entityform_drafts'] = $group;
  }
}

/**
 * Implements hook_form_alter().
 */
function feature_siasar_entityform_drafts_form_alter(&$form, &$form_state, $form_id) {
  $possible_entityforms = array_keys(entity_get_info('entityform')['bundles']);
  $form_id_clean = str_replace('_entityform_edit_form', '', $form_id);

  if (!in_array($form_id_clean, $possible_entityforms)) return;

  //Attach after_build function for removing field requirements
  $form['#after_build'][] = 'feature_siasar_entityform_drafts_remove_requirements';

}

/**
 * Implements hook_form_FORM_ID_alter().
 * Translate entityform labels.
 */
function feature_siasar_entityform_drafts_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form_state['view']->name !== 'draft_entityforms') return;

  module_load_include('inc', 'siasar_entityform_alter', 'siasar_entityform_alter.helpers');

  $form['type'] = _siasar_entityform_alter_create_entityforms_select_field('All');
}

/**
 * Remove requirements for entityform fields in case of workflow draft
 * @param $form
 * @param $form_state
 *
 * @return mixed
 */
function feature_siasar_entityform_drafts_remove_requirements(&$form, &$form_state) {
  if (!empty($form_state['triggering_element']['#workflow_sid'] && $form_state['triggering_element']['#workflow_sid'] == SIASAR_ENTITYFORM_STATE_DRAFT)) {
    _entityform_set_all_nested_props($form, array('#required' => FALSE));
  }
  return $form;
}