<?php

/**
 * Issue #499: Make sure field location is available during the user registration
 *
 * @param $sandbox
 */
function feature_siasar_user_update_7100(&$sandbox) {
  features_revert_module('feature_siasar_user');
}

/**
 * Issue 557. English issue.
 * User profile labels
 * https://gitlab.com/Admin_Siasar/SIASAR-2.0/issues/557
 *
 * @param $sandbox
 */
 function feature_siasar_theme_settings_update_7101() {
  features_revert_module('feature_siasar_user');
}
