<?php

/**
 * Implements hook_drush_command().
 */
function siasar_n11_manager_drush_command() {
  $items['siasar_load_n11'] = array(
      'description' => 'Load N11 manually',
      'aliases' => array('siasar-ln11'),
      'arguments' => array(
        'country_code' => 'Country code',
        'vocabulary vocab_machine_name name' => 'Vocabulary machine name',
        'file_uri' => 'CSV File URI (public://file.csv)',
        'skip' => 'Number of lines to skip',
        'linex' => 'Number of lines to process',
      ),
      'callback' => 'drush_siasar_load_n11',
      'examples' => array(
        'drush siasar-ln11 PE division_administrativa public://file.csv 0 1000' => 'Processes the first 1000 lines of the N11 for PERU.',
      ),
      'required-arguments' => TRUE,
      'bootstrap' => DRUSH_BOOTSTRAP_DRUPAL_FULL,
    );

    return $items;
}

/**
 * Load N11 table from CSV file (separated by ;) from the command line
 * This is a Drush command callback.
 *
 * @param string $country_code
 * @param string $vocab_machine_name
 * @param string $file_uri
 * @param integer $skip
 * @param int $lines
 * @return void
 */
function drush_siasar_load_n11($country_code, $vocab_machine_name, $file_uri = 'public://file.csv', $skip = 0, $lines = NULL) {
  module_load_include('inc', 'siasar_n11_manager', 'inc/siasar_n11_manager.helpers');

  $error_in_command_line = siasar_n11_manager_load_n11_error_check($country_code, $vocab_machine_name, $file_uri);
  if ($error_in_command_line)
    return;

  $vocab = taxonomy_vocabulary_machine_name_load($vocab_machine_name);

  $csv = array_map('str_getcsv', file('public://file.csv'));

  $terms_processed = array();

  $lines_processed = 0;
  foreach($csv as $chunk) {

    if ($skip) {
      $skip--;
      continue;
    }

    $terms_processed_level = &$terms_processed;
    $parent_term_id = 0;
    for($i = 0; $i < count($chunk) -1; $i++) {
      $term_name = $chunk[$i];

      if (!isset($terms_processed_level[$term_name])) {

        $term = siasar_n11_manager_get_taxonomy_by_name_and_country($vocab_machine_name, $term_name, $parent_term_id, $country_code);
        if (count($term)) {
          $term = reset($term);
        }

        if (!$term) {
          $term = new stdClass();

          $term->parent = $parent_term_id;
          $term->name = $term_name;
          $term->vid = $vocab->vid;
          $term->field_pais[LANGUAGE_NONE][0]['iso2'] = $country_code;

          taxonomy_term_save($term);

        }

        $parent_term_id = $term->tid;
        $terms_processed_level[$term_name] = array(
          'tid' => $term->tid,
          'children' => array()
        );

      } else {
        $parent_term_id = $terms_processed_level[$term_name]['tid'];
      }
      $terms_processed_level = &$terms_processed_level[$term_name]['children'];
    }

    $lines_processed++;

    if ($lines && $lines_processed >= $lines) {
      break;
    }
  }

  drupal_set_message('Lines processed: ' . $lines_processed);
}
