<?php

/**
 * Alter results on the Field Collection services call.
 *
 * @param $controller
 *   Controller definition
 * @param array $args
 *   Arguments passed to services callback
 * @param array $result
 *   Array of results that can be altered
 *
 * @see services_controller_execute()
 * @see services.runtime.inc
 */
function siasar_services_field_collection_alter_services_request_postprocess_alter($controller, $args, &$result) {

  if (arg(1) == 'field_collection_structure' and arg(2) !== null) { // At this moment, only field collection structure is considered for changes.
    _siasar_services_field_collection_alter_get_referenced_entityform_name($args[0], $result);
  }

}

/**
 * Gets entity name where a entityform is being referenced and this entity has a "field_entity_name" value set.
 * It traverses all fields on the Field Collection.
 *
 * @param string $arg
 *   First argument passed to services callback
 * @param array $result
 *   Array of results that can be altered (passed by reference)
 */
function _siasar_services_field_collection_alter_get_referenced_entityform_name($arg, &$result) {

  if (!is_array($result)) return;

  foreach ($result[$arg] as &$field) {
    if (!isset($field['settings']['resource']) or $field['settings']['resource'] !== 'entityform' or empty($field['settings']['allowed_values'])) {
      continue;
    }

    $entities_list = array_keys($field['settings']['allowed_values']);
    $entities = entity_load($field['settings']['resource'], $entities_list);

    foreach ($entities as $k => $e) {
      $wrapper = entity_metadata_wrapper($field['settings']['resource'], $e);
      $value = isset($e->field_entity_name) ? $wrapper->field_entity_name->value() : null;
      if (is_string($value)) {
        $field['settings']['allowed_values'][$k] = $value;
      }
    }
  }
}