<?php

/**
 * Implements hook_form_alter().
 */
function siasar_entityform_alter_form_alter(&$form, &$form_state, $form_id) {

  $possible_entityforms = array_keys(entity_get_info('entityform')['bundles']);
  $form_id_clean = str_replace('_entityform_edit_form', '', $form_id);

  if(!in_array($form_id_clean, $possible_entityforms)) return;

  $module_path = drupal_get_path('module', 'siasar_entityform_alter');

  drupal_add_js($module_path . '/js/siasar_entityform_alter.validate_button.js');
  $form_wrapper = entity_metadata_wrapper('entityform', $form_state['entityform']);
  if (isset($form['field_cuestionario_validado'])) {
    $form['field_cuestionario_validado']['#access'] = (user_access('validate entityforms') && !$form_wrapper->draft->value());
  }

  _siasar_entityform_alter_set_default_country($form);
  _siasar_entityform_alter_hide_validate_if_new($form, $form_state);
  _siasar_entityform_alter_build_validate_button($form, $form_state);
  _siasar_entityform_alter_process_country_field($form);
  _siasar_entityform_alter_revisions($form, $form_state, $form_id);
}

/**
 * Implements hook_permission().
 */
function siasar_entityform_alter_permission() {
  return array(
    'validate entityforms' => array(
      'title' => t('Validate entityforms'),
      'description' => t('User can validate entityforms and browse results for more info on validated/not validated forms.'),
    )
  );
}

/**
 * Helper function to set default country value from user if needed.
 */
function _siasar_entityform_alter_set_default_country(&$form) {
  global $user;
  $form_item_pais = &$form['field_pais'][LANGUAGE_NONE];

  if (!isset($form_item_pais['#default_value'][0])) {
    $user_country_iso2 = user_load($user->uid)->field_pais[LANGUAGE_NONE][0]['iso2'];
    $form_item_pais['#default_value'][0] = $user_country_iso2;
  }
}


/**
 * Helper function to hide Validate field if form is new.
 */
function _siasar_entityform_alter_hide_validate_if_new(&$form, $form_state) {
  if (empty($form_state['entityform']->entityform_id) && isset($form['field_cuestionario_validado'])) {
    $form['field_cuestionario_validado']['#access'] = false;
  }
}

/**
 * Helper function to build validate HTML button to replace the checkbox if:
 * a) form is NOT new. AND...
 * b) field 'field_cuestionario_validado' is set.
 */
function _siasar_entityform_alter_build_validate_button(&$form, $form_state) {
  if (empty($form_state['entityform']->entityform_id) || !isset($form['field_cuestionario_validado'])) return;

  $entityform = $form_state['entityform'];

  // Not all entityforms have this field, while entityforms form have them because of the form alter
  if (!isset($entityform->field_cuestionario_validado)) return;

  $actions_container = &$form['actions'];
  $form_wrapper = entity_metadata_wrapper('entityform', $entityform);
  $is_validated = $form_wrapper->field_cuestionario_validado->value();

  if(is_object($form_wrapper->draft) && (bool)$form_wrapper->draft->value()) return;

  if ($is_validated) {
    $status = 'validated';
    $label = 'Legacy: ' . t('Validated');
  } else {
    $status = 'not-validated';
    $label = 'Legacy: ' . t('Validate');
  }

  $validate_button = array(
    '#type' => 'button',
    '#value' => $label,
    '#attributes' => array(
      'status' => $status,
    ),
    '#button_type' => 'validate',
    '#name' => 'validate_button',
    '#weight' => -1,
  );

  $actions_container['validate'] = $validate_button;
}

/**
 * Helper function to filter out all countries that are not SIASAR members,
 * using taxonomy 'paises' as reference.
 */
function _siasar_entityform_alter_process_country_field(&$form) {
  module_load_include('inc', 'siasar_entityform_alter', 'siasar_entityform_alter.helpers');

  $field_pais_options = &$form['field_pais'][LANGUAGE_NONE]['#options'];
  $members = _siasar_entityform_alter_get_member_countries();

  $field_pais_options = _siasar_entityform_alter_filter_out_countries_from_options($field_pais_options, $members);
}

/**
* Implements hook_date_select_process_alter().
*/
function siasar_entityform_alter_date_select_process_alter(&$element, &$form_state, $context) {
  if ($element['#date_format'] !== 'Y') return;

  $array = $element['year']['#options'];

  // array_shift screws array keys, we need a more custom approach.
  reset($array);
  $key = key($array);
  $first = array($key => $array[$key]);
  unset($array[$key]);

  $array = array_reverse($array, true);
  $array = $first + $array;

  $element['year']['#options'] = $array;
}

/**
 * Process the revisions fieldset so it will not be displayed to any user
 * and it will be handled by the backend
 *
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function _siasar_entityform_alter_revisions(&$form, &$form_state, $form_id) {
  if (!empty($form['#entity']) && $form['#entity'] instanceof Entityform) {
    $form['revision_fieldset']['#access'] = FALSE;
  }
}

/**
 * Implements hook_entity_presave().
 *
 * It handles the transitions of entityforms in order to create revisions when
 * the form goes from validated to draft
 */
function siasar_entityform_alter_entity_presave($entity, $entity_type) {

  $field = 'field_status';
  $wrapper = entity_metadata_wrapper($entity_type, $entity);

  if ($entity_type == 'entityform' && isset($entity->original) && isset($wrapper->$field)) {
    $previous_value = $entity->original;

    $previous_sid = workflow_node_current_state($previous_value, $entity_type, $field);
    $new_sid = workflow_node_current_state($entity, $entity_type, $field);

    if ($previous_sid != $new_sid) {
      $old_state = workflow_state_load($previous_sid);
      $new_state = workflow_state_load($new_sid);

      if ($old_state && $new_state && $old_state->getName() == 'validated' && $new_state->getName() == 'draft') {
        $entity->default_revision = TRUE;
        $entity->is_new_revision = TRUE;
      }
    }
  }
}

/**
 * Implements hook_action_info().
 */
function siasar_entityform_alter_action_info() {
  module_load_include('inc', 'siasar_entityform_alter', 'siasar_entityform_alter.vbo');
  return _siasar_entityform_alter_action_info();
}

/**
 * Implements hook_entityform_to_revision_query_target_entities_alter()
 *
 * @param \EntityFieldQuery $query
 * @param \Entityform $entityform
 */
function siasar_entityform_alter_entityform_to_revision_query_target_entities_alter(&$query, $entityform) {
  $wrapper = $entityform->wrapper();
  $location = $wrapper->field_entidad_local->value();
  if ($location) {
    $query->fieldCondition('field_entidad_local', 'tid', $location->tid);
  }

  $country = $wrapper->field_pais->value();
  if ($country) {
    $query->fieldCondition('field_pais', 'iso2', $country->iso2);
  }
}

/**
 * Implements hook_preprocess_entityforms_target_table().
 *
 * @param $variables
 */
function siasar_entityform_alter_preprocess_entityforms_target_table(&$variables) {
  $variables['element']['#header'] = array(
    'name' => t('Name'),
    'location' => t('Location'),
    'date' => t('Date'),
    'digitizer' => t('Digitizer'),
    'interviewer' => t('Interviewer'),
    'type' => t('Type'),
    'operations' => t('Operations'),
  );

  $variables['element']['#empty'] = t('No questionnaires available for converting to revision.');

  foreach ($variables['element']['#options'] as $key => &$value) {
    /**
     * @var \EntityStructureWrapper $entityform
     */
    $entityform = $value['entityform']->wrapper();
    $entidad_local = $entityform->field_entidad_local->value();
    $pais = $entityform->field_pais->value();

    $digitizer = $entityform->user->value();

    $interviewer_name = '-';
    if (isset($entityform->field_user_reference)) {
      $interviewer = $entityform->field_user_reference->value();
      $interviewer_name = $interviewer->name;
    }

    $date = '-';
    if ($entityform->created->value()) {
      $date = format_date(REQUEST_TIME, 'short', $entityform->created->value());
    }

    $entity_uri = entity_uri('entityform', $entityform->value());

    $value = array(
      'name' => $entityform->field_entity_name->value(),
      'location' => $pais->name . ' ' . $entidad_local->name,
      'date' => $date,
      'digitizer' => $digitizer->name,
      'interviewer' => $interviewer_name,
      'type' => $entityform->getBundle(),
      'operations' => l('view', $entity_uri['path']),
    );

    $variables['element'][$key]['#title'] = '&nbsp;';
  }
}