<?php

/**
 * Implements hook_form_alter().
 */
function siasar_entityform_alter_form_alter(&$form, &$form_state, $form_id) {

  $possible_entityforms = array_keys(entity_get_info('entityform')['bundles']);
  $form_id_clean = str_replace('_entityform_edit_form', '', $form_id);

  if(!in_array($form_id_clean, $possible_entityforms)) return;

  $module_path = drupal_get_path('module', 'siasar_entityform_alter');

  drupal_add_js($module_path . '/js/siasar_entityform_alter.validate_button.js');

  _siasar_entityform_alter_set_default_country($form);
  _siasar_entityform_alter_hide_validate_if_new($form, $form_state);
  _siasar_entityform_alter_build_validate_button($form, $form_state);
}


/**
 * Helper function to set default country value from user if needed.
 */
function _siasar_entityform_alter_set_default_country(&$form) {
  global $user;
  $form_item_pais = &$form['field_pais'][LANGUAGE_NONE];

  if (!isset($form_item_pais['#default_value'][0])) {
    $user_country_iso2 = user_load($user->uid)->field_pais[LANGUAGE_NONE][0]['iso2'];
    $form_item_pais['#default_value'][0] = $user_country_iso2;
  }
}

/**
 * Helper function to hide Validate field if form is new.
 */
function _siasar_entityform_alter_hide_validate_if_new(&$form, $form_state) {
  if (empty($form_state['entityform']->entityform_id) && isset($form['field_cuestionario_validado'])) {
    $form['field_cuestionario_validado']['#access'] = false;
  }
}

/**
 * Helper function to build validate HTML button to replace the checkbox if:
 * a) form is NOT new. AND...
 * b) field 'field_cuestionario_validado' is set.
 */
function _siasar_entityform_alter_build_validate_button(&$form, $form_state) {
  if (empty($form_state['entityform']->entityform_id) || !isset($form['field_cuestionario_validado'])) return;

  $actions_container = &$form['actions'];
  $form_wrapper = entity_metadata_wrapper('entityform', $form_state['entityform']);
  $is_validated = $form_wrapper->field_cuestionario_validado->value();
  $form_status = $is_validated
    ? 'validated'
    : 'not-validated';

  $validate_button = array(
    '#type' => 'button',
    '#value' => t('Validate'),
    '#attributes' => array(
      'class' => $button_classes,
      'status' => $form_status,
    ),
    '#button_type' => 'validate',
    '#name' => 'validate_button',
    '#weight' => -1,
  );

  $actions_container['validate'] = $validate_button;

    $form = $form;
}


/**
* Implements hook_date_select_process_alter().
*/
function siasar_entityform_alter_date_select_process_alter(&$element, &$form_state, $context) {
  if ($element['#date_format'] !== 'Y') return;

  $array = $element['year']['#options'];

  // array_shift screws array keys, we need a more custom approach.
  reset($array);
  $key = key($array);
  $first = array($key => $array[$key]);
  unset($array[$key]);

  $array = array_reverse($array, true);
  $array = $first + $array;

  $element['year']['#options'] = $array;
}
