<?php
/**
 * Implementation of hook_services_resources().
 */
function siasar_services_counter_services_resources() {
  return array(
    'entity_count' => array(
      'operations' => array(
        'index' => array(
          'help' => 'Retrieves total number of entities saved, by type. Parameters: entity type, bundle.',
          'callback' => '_siasar_services_counter_entity_count',
          'args' => array(
            array(
              'name' => 'entity_name',
              'type' => 'string',
              'description' => '',
              'source' => array('path' => 0),
              'optional' => FALSE,
            ),
            array(
              'name' => 'bundle',
              'type' => 'string',
              'description' => '',
              'source' => array('path' => 1),
              'optional' => TRUE,
            ),
            array(
              'name' => 'parameters',
              'type' => 'array',
              'description' => '',
              'source' => array('param' => 'parameters'),
              'optional' => TRUE,
              'default value' => array(),
            )
          ),
          'access arguments' => array('access content'),
        ),
      ),
    ),
  );
}

/**
 * Callback for 'entity_count' endpoint.
 * Delivers number of saved entities by type and bundle.
 *
 * @param string $entity_name
 *   Entity name. Required.
 *
 * @param string $bundle
 *   Entity bundle.
 *
 * @param array $parameters
 *   GET parameters
 *
 * @return array
 *   Keyed array [bundle_machine_name] => int
 */
function _siasar_services_counter_entity_count($entity_name, $bundle, $parameters) {
  $bundles = $bundle
    ? array($bundle)
    : array_keys(entity_get_info($entity_name)['bundles']);

  foreach ($bundles as $b) {
    $total[$b] = _siasar_services_counter_get_totals_per_bundle($entity_name, $b, $parameters);
  }

  return $total;
}

/**
 * Helper funtion. Counts all existing entities of a given class, by bundle.
 *
 * @param string $entity_name
 *   Entity machine name
 *
 * @param array $bundles
 *   Bundles machine names
 *
 * @return array
 *   Keyed array [entityform_machine_name] => int
 */
function _siasar_services_counter_get_totals_per_bundle($entity_name, $bundle, $parameters) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', $entity_name)
    ->entityCondition('bundle', $bundle)
    ->count();

  if (!empty($parameters)) {
    _siasar_services_counter_add_parameters_to_query($query, $parameters);
  }

  return $query->execute();
}


function _siasar_services_counter_add_parameters_to_query($query, $parameters) {
  foreach($parameters as $k => $p) {
    // Is it a field?
    $k_prefix = 'field_' . $k;
    $field_info = field_info_field($k_prefix);
    if ($field_info) {
      $column = array_keys($field_info['columns'])[0];
      $query->fieldCondition($k_prefix, $column, $p, '=');
    } else {
      $query->propertyCondition($k, 'value', $p);
    }
  }
}
