<?php

/**
 * Implements hook_services_resources().
 */
function siasar_entityform_change_service_services_resources() {
  $api = [
    'siasar_entityform_change' => [
      'operations' => [
        'index' => [
          'help' => 'Retrieves forms changed for "finished" status or removed',
          'callback' => '_siasar_entityform_change_service_services_index',
          'file' => ['file' => 'services.inc', 'module' => 'siasar_entityform_change_service'],
          'access callback' => 'user_access',
          'access arguments' => ['access content'],
          'access arguments append' => FALSE,
          'args' => [
            [
              'name' => 'date_start',
              'type' => 'timestamp',
              'description' => 'Start date range for entityform filter',
              'source' => 'param',
              'optional' => TRUE,
            ],
            [
              'name' => 'date_end',
              'type' => 'timestamp',
              'description' => 'End date range for entityform filter',
              'source' => 'param',
              'optional' => TRUE,
            ]
          ]
        ]
      ]
    ],
  ];

  return $api;
}
