<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Custom logic to deal with the new field, which will store closed versions.
 */
function siasar_workflow_entityform_presave($entityform) {
  module_load_include('inc', 'siasar_workflow', 'inc/siasar_workflow.helpers');

  if ($entityform->entityform_id === '' || _siasar_workflow_check_transition($entityform, 'validated', 'closed') === false)
    return;

  $wrapper = $entityform->wrapper();
  $closed = $wrapper->field_closed_revisions->value();

  $closed[] = $entityform->vid;
  $wrapper->field_closed_revisions->set($closed);

  $entityform->revision = true;
  $entityform->is_new_revision = true;
}

/**
 * Implementation of hook_preprocess_field()
 * It adds Timestamp data to the vars[items] array.
 */
function siasar_workflow_preprocess_field(&$vars) {
  if ($vars['element']['#field_name'] != 'field_closed_revisions')
    return;

  module_load_include('inc', 'siasar_workflow', 'inc/siasar_workflow.helpers');

  $entityform_id = $vars['element']['#object']->entityform_id;
  $all_revisions = _siasar_workflow_get_revision_data($entityform_id);

  foreach ($vars['items'] as &$v) {
    $vid = (int) $v['#markup'];

    $v['vid'] = $vid;
    $v['timestamp'] = $all_revisions[$vid]->changed;
  }
}
