<?php

/*
 * Implementation of hook_form_alter()
 */
function entityform_prepopulate_form_alter(&$form, &$form_state, $form_id){
    //dsm($form_id);
    $user = $GLOBALS['user'];
    switch($form_id) {
        case 'comunidad_entityform_edit_form':
        case 'sistema_entityform_edit_form':
        case 'prestador_de_asistencia_t_cnica_entityform_edit_form':
        case 'prestador_de_servicio_entityform_edit_form':
            populate_default_pollster($form, $user);
        break;
        case 'user_profile_form':
            populate_default_country($form, $user); 
        break;
    }
    
}

/*
 * Implementation of hook_user_update()
 */
function entityform_prepopulate_user_update(&$edit, $account, $category) {
    // clear cached shs data from the division administrativa taxonomy, so dat the next time it shows up updated contextual values
     drupal_static_reset('shs_term_get_children');
     cache_clear_all('shs:', 'cache', TRUE);

    // update the current lagunage according to user's preferences
    $languages = get_language_list();     // debug($langs, '$langs');
    variable_set('language_default', $languages[$account->language]);
}

/*
 * Implementation of hook_user_update()
 */
function entityform_prepopulate_user_presave(&$edit, $account, $category) {
    // @todo update available/timezones based on user country
}

function get_language_list($all = FALSE) {
  if ($all) {
    $languages = language_list();
  }
  else {
    $languages = language_list('enabled');
    $languages = $languages[1];
  }
  return $languages;
}

function populate_default_pollster(&$form, $user){
    if(isset($form['field_user_reference'])){        
        if(in_array("Encuestador", $user->roles)){     //TODO: ASSERT Encuestador role exits
            $default_value = array($user->uid);
            set_default_value($form['field_user_reference'], $default_value, TRUE);
        }        
    }
}

function populate_default_country(&$form, $user){
    // @todo fix field_pais and disable editing in case of a digitador updating an encuestador profile
    // can an encuestador change the country??? NO, then disable/hide if the profile is from an encuestador 
}

function set_default_value(&$field, $default_value, $disable = FALSE, $access = TRUE){
    if($field){
        $field['und']['#default_value'] = $default_value; 
        if($field['#disabled'] = $disable){
            $field['#access'] = $access;
        }
    }
}
